#' Plot Spawning Biomass Comparisons
#'
#' @description
#' Extracts spawning biomass estimates (or a specified variable) and their standard errors 
#' from one or more model runs, calculates 95% confidence intervals, and plots the 
#' comparative time series.
#'
#' @param ... One or more model output objects, or a single list containing multiple model 
#'   output objects. Objects must contain a TMB `sdreport` object (`$sd`) and a report list 
#'   with a `years` vector (`$rpt$years`).
#' @param var_pattern A character string containing a regular expression pattern used to 
#'   filter the variable of interest from the `sdreport` object. Default is `"^spawn_bio"`.
#' @param palette A character string specifying the color palette to use from the `scico` 
#'   package. Default is `"roma"`.
#' @param base_size A numeric value specifying the base font size passed to 
#'   `afscassess::theme_report()`. Default is `16`.
#'
#' @return A `ggplot` object displaying the time series comparison with shaded 95% 
#'   confidence intervals.
#' @export
plot_ssb_comp <- function(..., var_pattern = "^spawn_bio", 
                              palette = "roma", 
                              base_size = 16) {
  
  # Capture model inputs
  mods <- list(...)
  
  # Allow passing a single list of models (e.g., plot_ssb_comp(model_list))
  if (length(mods) == 1 && is.list(mods[[1]]) && !("sd" %in% names(mods[[1]]))) {
    mods <- mods[[1]]
  }
  
  # Extract names for plot legends
  mod_names <- names(mods)
  expr_names <- as.character(substitute(list(...)))[-1]
  
  if (is.null(mod_names)) {
    mod_names <- expr_names
  } else {
    unnamed <- mod_names == ""
    if (any(unnamed)) {
      mod_names[unnamed] <- expr_names[unnamed]
    }
  }
  
  # Extract spawning biomass and calculate CIs across all models
  df <- purrr::map2_dfr(mods, mod_names, function(mod, id_name) {
    summary(mod$sd, select = "all") %>%
      as.data.frame() %>%
      rownames_to_column(var = "item") %>%
      as_tibble() %>%
      rename(
        value = Estimate,
        se = `Std. Error`
      ) %>%
      filter(stringr::str_detect(item, var_pattern)) %>%
      mutate(
        year = mod$rpt$years,
        lci = value - 1.96 * se,
        uci = value + 1.96 * se,
        id = id_name
      )
  })
    # Render Plot
  ggplot(df, aes(x = year, y = value, color = id, fill = id)) +
    geom_ribbon(aes(ymin = lci, ymax = uci), alpha = 0.2, color = NA) +
    geom_line() +
    scico::scale_color_scico_d(name = "Model", palette = palette) +
    scico::scale_fill_scico_d(name = "Model", palette = palette) +
    labs(x = "Year", y = "Spawning biomass (t)") +
    afscassess::theme_report(base_size = base_size)
}


#' Remove Terminal Years of Data (Retrospective Drop)
#'
#' @description
#' Conducts a retrospective-style data drop by setting the terminal (most recent) years 
#' of a specific data index to zero, and then re-runs the model.
#'
#' @param output A list containing the baseline model output. Must contain the data (`$dat`), 
#'   objective function environment (`$obj`), the compiled model (`$model`), and bounds 
#'   (`$lower`, `$upper`).
#' @param item A character string specifying the name of the data index in the `$dat` list 
#'   to modify. Default is `"srv_ind"`.
#' @param yrs A numeric value indicating the number of trailing years at the end of the 
#'   specified data vector to remove (set to 0). Default is `2`.
#'
#' @return A new model run object generated by `run_model()`.
#' @export
#' 
rmv <- function(output, item = "srv_ind", yrs = 2) {
  dat = output$dat
  f = output$model
  l = output$lower
  u = output$upper
  map = output$obj$env$map
  pars = output$obj$env$parList()

  idx <- tail(seq_along(dat[[item]]), yrs)
  dat[[item]][idx] <- 0

  new_run <- run_model(
      model = f, 
      data = dat, 
      pars = pars, 
      map = map, 
      lower = l, 
      upper = u
    )
  new_run
}

#' Drop Data Weight for Sensitivity Analysis
#'
#' @description
#' Performs a sensitivity by dropping the weight of a specific 
#' data component entirely (setting it to zero) and re-running the model.
#'
#' @param output A list containing the baseline model output. Must contain the data (`$dat`), 
#'   objective function environment (`$obj`), the compiled model (`$model`), and bounds 
#'   (`$lower`, `$upper`).
#' @param item A character string specifying the name of the weighting parameter in the 
#'   `$dat` list to set to zero. Default is `"srv_wt"`.
#'
#' @return A new model run object generated by `run_model()`.
#' @export
drop_wt <- function(output, item = "srv_wt") {
  dat = output$dat
  f = output$model
  l = output$lower
  u = output$upper
  map = output$obj$env$map
  pars = output$obj$env$parList()

  if(item == "catch_wt" & length(dat$catch_wt>1)) {
    dat$catch_wt = rep(0, length(dat$catch_wt))
  } else {
    dat[[item]] <- 0
  }

  new_run <- run_model(
      model = f, 
      data = dat, 
      pars = pars, 
      map = map, 
      lower = l, 
      upper = u
    )
  new_run
}